apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/product-service
    repoURL: https://github.com/TejiriH/ecommerce-api.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
